#index:
#    path: /
#    controller: App\Controller\DefaultController::index

especialidades:
  path: /especialidades
  controller: App\Controller\EspecialidadesController::getAll
  methods:
    - GET

especialidade:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadesController::getOne
  methods:
    - GET

addEspecialidade:
  path: /especialidades
  controller: App\Controller\EspecialidadesController::novo
  methods:
    - POST

editEspecialidade:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadesController::edit
  methods:
    - PUT

removeEspecialidade:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadesController::remove
  methods:
    - DELETE



medicos:
  path: /medicos
  controller: App\Controller\MedicosController::getAll
  methods:
    - GET

medico:
  path: /medicos/{id}
  controller: App\Controller\MedicosController::getOne
  methods:
    - GET

addMedico:
  path: /medicos
  controller: App\Controller\MedicosController::novo
  methods:
    - POST
    
editMedico:
  path: /medicos/{id}
  controller: App\Controller\MedicosController::edit
  methods:
    - PUT

removeMedico:
  path: /medicos/{id}
  controller: App\Controller\MedicosController::remove
  methods:
    - DELETE



